basePath: /api
definitions:
  github_com_fisker_zjump-backend_internal_model.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  github_com_fisker_zjump-backend_internal_model.SystemUser:
    properties:
      authType:
        description: 认证信息 (必须明确选择 password 或 key，不支持 auto)
        type: string
      createdAt:
        type: string
      createdBy:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        description: 显示名称
        type: string
      passphrase:
        type: string
      password:
        type: string
      priority:
        description: 其他设置
        type: integer
      privateKey:
        type: string
      protocol:
        description: 协议和设置
        type: string
      status:
        description: active, inactive
        type: string
      updatedAt:
        type: string
      username:
        description: OS用户名
        type: string
    type: object
  github_com_fisker_zjump-backend_internal_model.UserGroup:
    properties:
      color:
        description: 显示相关
        type: string
      createdAt:
        type: string
      createdBy:
        type: string
      description:
        type: string
      icon:
        type: string
      id:
        type: string
      name:
        type: string
      priority:
        type: integer
      status:
        description: active, inactive
        type: string
      updatedAt:
        type: string
    type: object
  internal_api_handler.CreatePermissionRuleRequest:
    properties:
      createdAt:
        type: string
      createdBy:
        type: string
      description:
        type: string
      enabled:
        description: 状态
        type: boolean
      hostGroupId:
        description: 资产范围
        type: string
      hostGroupIds:
        description: 多个主机组ID
        items:
          type: string
        type: array
      hostIds:
        description: JSON数组，指定主机ID列表
        type: string
      id:
        type: string
      name:
        type: string
      priority:
        type: integer
      systemUserId:
        description: 系统用户
        type: string
      systemUserIds:
        description: 多个系统用户ID
        items:
          type: string
        type: array
      updatedAt:
        type: string
      userGroupId:
        description: 授权对象
        type: string
      validFrom:
        description: 时间限制
        type: string
      validTo:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@zjump.com
    name: API Support
  description: ZJump 堡垒机系统 API 文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: ZJump API
  version: "2.0"
paths:
  /api/permission-rules:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取授权规则列表
      tags:
      - permission-rules
    post:
      consumes:
      - application/json
      parameters:
      - description: Permission Rule
        in: body
        name: rule
        required: true
        schema:
          $ref: '#/definitions/internal_api_handler.CreatePermissionRuleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 创建授权规则
      tags:
      - permission-rules
  /api/permission-rules/{id}:
    delete:
      parameters:
      - description: Permission Rule ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 删除授权规则
      tags:
      - permission-rules
    get:
      parameters:
      - description: Permission Rule ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取单个授权规则
      tags:
      - permission-rules
    put:
      consumes:
      - application/json
      parameters:
      - description: Permission Rule ID
        in: path
        name: id
        required: true
        type: string
      - description: Permission Rule
        in: body
        name: rule
        required: true
        schema:
          $ref: '#/definitions/internal_api_handler.CreatePermissionRuleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 更新授权规则
      tags:
      - permission-rules
  /api/permission-rules/by-host-group:
    get:
      parameters:
      - description: Host Group ID
        in: query
        name: hostGroupId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取主机组的授权规则
      tags:
      - permission-rules
  /api/permission-rules/by-user-group:
    get:
      parameters:
      - description: User Group ID
        in: query
        name: userGroupId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取用户组的授权规则
      tags:
      - permission-rules
  /api/system-users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取系统用户列表
      tags:
      - system-users
    post:
      consumes:
      - application/json
      parameters:
      - description: System User
        in: body
        name: systemUser
        required: true
        schema:
          $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.SystemUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 创建系统用户
      tags:
      - system-users
  /api/system-users/{id}:
    delete:
      parameters:
      - description: System User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 删除系统用户
      tags:
      - system-users
    get:
      parameters:
      - description: System User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取单个系统用户
      tags:
      - system-users
    put:
      consumes:
      - application/json
      parameters:
      - description: System User ID
        in: path
        name: id
        required: true
        type: string
      - description: System User
        in: body
        name: systemUser
        required: true
        schema:
          $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.SystemUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 更新系统用户
      tags:
      - system-users
  /api/system-users/available:
    get:
      parameters:
      - description: Host ID
        in: query
        name: hostId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取用户可用的系统用户列表
      tags:
      - system-users
  /api/system-users/check-permission:
    get:
      parameters:
      - description: Host ID
        in: query
        name: hostId
        required: true
        type: string
      - description: System User ID
        in: query
        name: systemUserId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 检查用户权限
      tags:
      - system-users
  /api/user-groups:
    get:
      parameters:
      - description: Include members
        in: query
        name: withMembers
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取用户组列表
      tags:
      - user-groups
    post:
      consumes:
      - application/json
      parameters:
      - description: User Group
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.UserGroup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 创建用户组
      tags:
      - user-groups
  /api/user-groups/{id}:
    delete:
      parameters:
      - description: User Group ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 删除用户组
      tags:
      - user-groups
    get:
      parameters:
      - description: User Group ID
        in: path
        name: id
        required: true
        type: string
      - description: Include members
        in: query
        name: withMembers
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取单个用户组
      tags:
      - user-groups
    put:
      consumes:
      - application/json
      parameters:
      - description: User Group ID
        in: path
        name: id
        required: true
        type: string
      - description: User Group
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.UserGroup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 更新用户组
      tags:
      - user-groups
  /api/user-groups/{id}/members:
    get:
      parameters:
      - description: User Group ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取用户组成员
      tags:
      - user-groups
    post:
      consumes:
      - application/json
      parameters:
      - description: User Group ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body with userId
        in: body
        name: request
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 添加用户到用户组
      tags:
      - user-groups
  /api/user-groups/{id}/members/{userId}:
    delete:
      parameters:
      - description: User Group ID
        in: path
        name: id
        required: true
        type: string
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 从用户组移除用户
      tags:
      - user-groups
  /api/user-groups/{id}/members/batch:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Group ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body with userIds
        in: body
        name: request
        required: true
        schema:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 批量添加成员
      tags:
      - user-groups
  /api/user-groups/by-user:
    get:
      parameters:
      - description: User ID
        in: query
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_fisker_zjump-backend_internal_model.Response'
      summary: 获取用户所在的所有用户组
      tags:
      - user-groups
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
